### ISSUE TITLE
remove ts files from npm package

### ISSUE THREAD

**Issue by saithis** [cstefanache/angular2-img-cropper#148]
We have noUnusedLocals activated in our tsconfig.json and when we import the ng2-img-cropper our build fails. this is because tsc applies the noUnusedLocals rule to the ts files in your npm package, which has unused locals. 

Could your please exclude the ts file from the npm package?

**Comment by cstefanache** [comment]
Fixed!

**Comment by wnabil** [comment]
version 0.8.3 also got same error but i can see the ts files
i downgraded the module to 0.8.1 until the fix on 0.8.3

**Comment by leosvelperez** [comment]
@cstefanache I'm seeing this issue closed but I'm still facing the same issue. The distributable package on npm still has the .ts files, it should have only the .d.ts. Having the .ts files causes compilation problems due to different linter rules and tsconfig configurations. I tried removing the .ts manually from the package and then it worked my project compilation as it should be.
