### ISSUE TITLE
Wait for img load to complete

### ISSUE THREAD

**Issue by frankfarzan** [cstefanache/angular2-img-cropper#39]
In the following code:

```
fileChangeListener($event) {
    var image:any = new Image();
    var file:File = $event.target.files[0];
    var myReader:FileReader = new FileReader();
    var that = this;
    myReader.onloadend = function (loadEvent:any) {
        image.src = loadEvent.target.result;
        that.cropper.setImage(image);
    };

    myReader.readAsDataURL(file);
}
```

After setting image source (imgage.src=...), you need to wait for image
to be loaded before calling setImage, otherwise there's a race condition.:

```
    image.onload = function () {
        that.cropper.setImage(image);
    };
    myReader.onloadend = function (loadEvent:any) {
        image.src = loadEvent.target.result;
    };
```

**Comment by frankfarzan** [comment]
You can easily repro this in Safari where out of band parameters are passed to ctx.getImageData()

**Comment by joerex** [comment]
Works for me @frankfarzan!

**Comment by cstefanache** [comment]
I can reproduce it only on Firefox ... Investigating now

**Comment by cstefanache** [comment]
The issue was fixed - I was able to reproduce it rarely on my computer but I noticed that the loadend event was fired before image was loaded. Fixed it using a setInterval and checked if nativeHeight > 0. Will be released on 0.6

**Comment by CamusAran** [comment]
I'm still having issues in firefox 50.1.0. The image doesn't get loaded the first time I select an image but every subsequent time it works fine. I tried both noFileInput false and true.
Works in Chrome.

ng2-img-cropper 0.7.6
angular 2.2.3

**Comment by mihaicrisan** [comment]
@CamusAran Had the same problem solved , in mageCropperComponent.ts 
`    public setImage(image: HTMLImageElement) {
        let self = this;

        this.intervalRef = window.setInterval(function() {
            //if (self.intervalRef) {clearInterval(self.intervalRef);}   <- REMOVE/COMMENT THIS
            if (image.naturalHeight > 0) {

                image.height = image.naturalHeight;
                image.width = image.naturalWidth;

                clearInterval(self.intervalRef);
                self.getOrientedImage(image, (img: HTMLImageElement) => {
                    self.cropper.setImage(img);
                    self.image.original = img;
                    let bounds = self.cropper.getCropBounds();
                    self.image.image = self.cropper.getCroppedImage().src;
                    self.onCrop.emit(bounds);
                });
            }
        }, 100);

    }`

**Comment by reactionic127** [comment]
@CamusAran 
How can I detect image load is success on frontend side?
